name: Build and Release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Make gradlew executable
      run: chmod +x ./gradlew

    - name: Build with Gradle
      run: ./gradlew clean build reobfJar

    - name: Extract version from build.gradle.kts
      run: |
        VERSION=$(grep '^version =' chatr/build.gradle.kts | sed 's/version = "\(.*\)"/\1/')
        echo "VERSION=$VERSION" >> $GITHUB_ENV

    - name: Upload JAR as artifact
      uses: actions/upload-artifact@v4
      with:
        name: Chatr-JAR
        path: chatr/build/libs/*.jar

    - name: Publish to Modrinth
      if: github.ref == 'refs/heads/main'
      uses: modrinth/action@v1
      with:
        token: ${{ secrets.MODRINTH_TOKEN }}
        project_id: 1AEV6tyB
        version_number: ${{ env.VERSION }}
        name: Chatr ${{ env.VERSION }}
        changelog: ${{ github.event.head_commit.message }}
        files: chatr/build/libs/*.jar
        loaders: |
          - paper
        game_versions: |
          - 1.21.1
        version_type: release

    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/v')
      uses: softprops/action-gh-release@v2
      with:
        files: chatr/build/libs/*.jar
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}